---
aliases:
- about-us
- about-hugo
- contact
author: Sydne Guevara
date: "2025-08-26"
description: Hugo, the world's fastest framework for building websites
title: About
output: html_document
---

Hi! I’m Sydne, a molecular biologist passionate about applying genetic and computational tools to develop innovative solutions in the biotechnology industry. I completed my undergraduate degree in Biology at the National University of Colombia, and later moved to Canada, where I earned a Master’s in Chemical Ecology at the University of Alberta and a PhD in Molecular Biology at the University of British Columbia.

Most of my research has focused on engineering plants to produce compounds of industrial and pharmaceutical interest. Along the way, I’ve worked with techniques such as CRISPR-Cas9, RNAseq, HPLC, and GC-MS. I love combining hands-on lab work with computational tools to drive innovation in biotechnology.

On this site, you’ll find an overview of my research, some of the computational tools I’ve developed, and a blog where I share interesting aspects of my work 🌿

This space is also my way of giving back: I’m committed to making my work accessible to Spanish-speaking communities interested in science and biotech. The site is fully bilingual, and I hope it helps inspire more innovation and collaboration in Latin America and beyond.

