---
aliases:
- about-us
- about-hugo
- contact
author: Sydne Guevara
date: "2023-04-13"
description: Hugo, the world's fastest framework for building websites
title: Perfil
---

¡Hola! Soy Sydne, bióloga molecular apasionada por utilizar herramientas genéticas y computacionales que tengan aplicaciones a nivel industrial. Completé mi pregrado en Biología en la Universidad Nacional de Colombia y luego me mudé a Canadá, donde realicé una maestría en Ecología Química en la Universidad de Alberta y mi doctorado en Biología Molecular de Plantas en la Universidad de British Columbia.

Mi investigación se ha centrado en modificar genéticamente la pared celular de las plantas para producir compuestos de interés industrial y farmacológico. Algunas de las técnicas con las que he trabajado incluyen CRISPR-Cas9, RNA-seq, HPLC y GC-MS. Me encanta combinar la investigación en el laboratorio con análisis de datos y bioinformática.

En este sitio encontrarás una visión general de mi investigación, algunas de las herramientas computacionales que he desarrollado y un blog donde comparto aspectos interesantes de mi trabajo 🌿
